name: Docs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Requirements
      run: sudo apt install doxygen sphinx-doc python3 libgtest-dev libgmock-dev valgrind
        && pip3 install sphinx-rtd-theme
        && pip3 install breathe
        && pip3 install sphinx-sitemap

    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Run CMake
      run: cmake .

    - name: Build the documentation
      run: make docs
    
    - name: Add .nojekyll
      run: touch docs/build/html/.nojekyll

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: docs/build/html # The folder the action should deploy.