name: GNU/Linux
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

    defaults:
      run:
        shell: bash

jobs:
  linux:
    name: Build project for GNU/Linux with ${{matrix.compiler.name}}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        compiler:
          - {name: GCC, cxx: g++}
          - {name: Clang, cxx: clang++}

    steps:
      - name: Checkout respository
        uses: actions/checkout@v3

      - name: Update git submodules
        run: git submodule update --init

      - name: Install dependencies
        run: sudo apt install libgtest-dev libgmock-dev valgrind libboost-all-dev

      - name: Run CMake
        run: cmake . -DCMAKE_CXX_COMPILER=${{matrix.compiler.cxx}}

      - name: Run tests
        id: runTests
        run: make all ExperimentalMemCheck

      - name: Read valgrind logs
        if: success() || failure()
        run: cat Testing/Temporary/MemoryChecker.*.log | cat
