name: GNU/Linux
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

    defaults:
      run:
        shell: bash

jobs:
  linux:
    name: ${{matrix.compiler}}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        compiler: ['g++', 'clang++']

    steps:
      - name: Checkout respository
        uses: actions/checkout@v3

      - name: Update git submodules
        run: git submodule update --init

      - name: Install dependencies
        run: sudo apt install python3-pip; pip3 install meson ninja

      - name: Install boost
        uses: MarkusJx/install-boost@v2.4.1
        id: install-boost
        with:
          boost_version: 1.81.0
          boost_install_dir: /tmp

      - name: Run Meson
        run: meson setup build -Db_sanitize=address
        env:
          BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
          CXX: ${{matrix.compiler}}

      - name: Compile the project
        run: ninja -C build

      - name: Run tests
        run: ninja -C build test

      - name: Read logs
        if: success() || failure()
        run: cat build/meson-logs/testlog.txt | cat
