name: Windows
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

    defaults:
      run:
        shell: bash

jobs:
  windows:
    name: ${{matrix.compiler.cxx}}
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        compiler:
          - {cxx: cl, ld : link}
          # - {cxx: g++, ld : lld}
          - {cxx: clang++, ld : lld}

    steps:
      - name: Checkout respository
        uses: actions/checkout@v3

      - name: Add MSVC dev cmd
        uses: ilammy/msvc-dev-cmd@v1

      - name: Update git submodules
        run: git submodule update --init

      - name: Install dependencies
        run: choco install python; pip3 install meson ninja

      - name: Install boost
        uses: MarkusJx/install-boost@v2.4.1
        id: install-boost
        with:
          boost_version: 1.81.0
          boost_install_dir: D:\boost
          toolset: msvc

      - name: Run Meson
        run: meson setup build
        env:
          BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
          CXX: ${{matrix.compiler.cxx}}
          CXX_LD: ${{matrix.compiler.ld}}

      - name: Compile the project
        run: ninja -C build

      - name: Run tests
        run: ninja -C build test

      - name: Read logs
        if: success() || failure()
        run: type build/meson-logs/testlog.txt
