name: Windows
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

    defaults:
      run:
        shell: bash

jobs:
  macos:
    name: ${{matrix.compiler.name}}
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        compiler:
          - {name: CL, cxx: cl}

    steps:
      - name: Checkout respository
        uses: actions/checkout@v3
      
      - name: Add MSVC dev cmd
        uses: ilammy/msvc-dev-cmd@v1

      - name: Update git submodules
        run: git submodule update --init

      - name: Install dependencies
        run: choco install python; pip3 install meson ninja

      - name: Run Meson
        run: cmd /v /c "set CXX=${{matrix.compiler.cxx}} && meson setup build -Dexe=disabled"

      - name: Compile and run tests
        id: runTests
        run: ninja -C build test  

      - name: Read logs
        if: success() || failure()
        run: type build/meson-logs/testlog.txt